name: label eden org runner group Default

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '*/1 * * * *'  # Every 1 minute

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: cd front-end && docker build . --file Dockerfile --tag calipso-front:$(date +%s)
